os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install mysql;
      brew link mysql;
      mysql.server start;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      sudo apt-get install -y mysql-server libmysqlclient-dev;
      sudo mysql_install_db;
    fi
  - mysql -u root --password="" -e 'create database test;'
  - eval "$(curl -sL swift.qutheory.io/travis)"
script:
  # Build MySQL 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      swift build -Xswiftc -I/usr/local/include/mysql -Xlinker -L/usr/local/lib;
      swift build --configuration release -Xswiftc -I/usr/local/include/mysql -Xlinker -L/usr/local/lib;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      swift build -Xswiftc -DNOJSON;
      swift build --configuration release -Xswiftc -DNOJSON;
    fi
  # Test MySQL
  - swift test
  