version: '2'

services:
  mysql-80:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: vapor_database
      MYSQL_USER: vapor_username
      MYSQL_PASSWORD: vapor_password
    ports:
      - 3306:3306
  mysql-57:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: vapor_database
      MYSQL_USER: vapor_username
      MYSQL_PASSWORD: vapor_password
    ports:
      - 3306:3306
  mysql-56:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: vapor_database
      MYSQL_USER: vapor_username
      MYSQL_PASSWORD: vapor_password
    ports:
      - 3306:3306
  mysql-55:
    image: mysql:5.5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: vapor_database
      MYSQL_USER: vapor_username
      MYSQL_PASSWORD: vapor_password
    ports:
      - 3306:3306
